### ISSUE TITLE
Linker error, cannot find "isfinite" symbol

### ISSUE THREAD

**Issue by greg-kennedy** [noirotm/flvmeta#17]
I am having issues building `flvmeta` on my FreeBSD machine.  The issue is that the `isfinite()` function, declared in `math.h`, requires linking against `libm.so` to actually use the symbol:

```
[100%] Linking C executable flvmeta
ld: error: undefined symbol: __isfinite
>>> referenced by json.c
>>>               CMakeFiles/flvmeta.dir/json.c.o:(json_emit_number)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
```

I can work around this problem on my machine by editing `src/CMakeLists.txt` and adding this line somewhere:
```target_link_libraries(flvmeta m)```

which does add `-lm` to the linker opts as expected.

Unfortunately I know practically nothing about CMake, so I cannot contribute a patch for this that wouldn't possibly break other things :(

**Comment by noirotm** [comment]
Hi Greg,
thank you for the bug report.

This is indeed an oversight from me, as the man page for isfinite clearly states to link to libm.
It turns out in Linux, GCC and Clang both use a builtin version of isfinite that does not require linking to libm 
(See https://code.woboq.org/userspace/glibc/math/math.h.html#911), so the CI didn't catch this.

I will do a fix to conditionally link to -lm if necessary.

**Comment by greg-kennedy** [comment]
Just cloned and tested this on my machine, it works now :)
